#!/bin/bash

SRC_DIR="/home/test/grub-0.97"
DIR="/home/test/cscope/grub"

files=cscope.files

set -x
echo "Finding relevant source files..."

mkdir -p $DIR
cd $DIR
find $SRC_DIR -name "*.[chS]" -print > $files

echo "Building cscope database..."
time cscope -q -k -b -i $files

ctags -I __THROW -I __THROWNL -I __attribute_pure__ -I __nonnull -I __attribute__ -I __wur -I __weak_alias --file-scope=yes --langmap=c:+.h,Asm:+.asm --languages=c,c++,Asm --links=yes --c-kinds=+p --c++-kinds=+p --fields=+iaS --extra=+q -R -f grub_tags $SRC_DIR

